name: gazette
description: La gazette au format numérique

publish_to: 'none'
version: 1.0.6

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0

  # Images
  image_picker: ^1.1.2

  # APIs
  http: ^1.2.2
  intl: ^0.19.0
  html: ^0.15.4

  # Common packages
  nb_utils: ^7.0.4
  google_fonts: ^6.2.1

  package_info_plus: ^8.0.2

  # Story
  story_view: ^0.16.5
  flutter_reaction_button: ^3.0.0+3

  # State Management Technique
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1
  pocketbase: ^0.18.1
  get: ^4.6.6
  get_storage: ^2.1.1
  cached_network_image: ^3.4.1
  syncfusion_flutter_pdfviewer: ^27.1.53
  flutter_localizations:
    sdk: flutter
  image_downloader_web: ^2.0.6
  super_clipboard: ^0.8.24

dependency_overrides:
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1

    #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true


  assets:
    - images/gazette/
    - images/gazette/icons/




