name: prokit_socialv
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_vector_icons: ^2.0.0

  # Images
  image_picker: ^1.1.2

  # APIs
  http: ^1.2.2
  intl: ^0.19.0
  html: ^0.15.4

  # Common packages
  nb_utils: ^7.0.4
  google_fonts: ^6.2.1

  package_info_plus: ^8.0.2

  # Story
  story_view: ^0.16.5
  flutter_reaction_button: ^3.0.0+3

  # State Management Technique
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

dependency_overrides:
  intl: ^0.19.0
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.12
  mobx_codegen: ^2.6.1

    #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true


  assets:
    - images/socialv/posts/
    - images/socialv/faces/
    - images/socialv/
    - images/socialv/icons/
    - images/socialv/gifs/




